### ISSUE TITLE
Could not send message to host

### ISSUE THREAD

**Issue by mitrevski94** [wetalkit/supercup#23]
"Send message" button does not work. Additionally on smaller screens the button dissapear, only "Close" is there. 
Error in console:
"Uncaught TypeError: Cannot read property 'response' of undefined"
```
        }).fail(function (response) {
        
            **var data = response.responseJSON;**
            if(!data.response){
              bootstrap_alert.warning(data.data.join('<br/>'));
            }

```
http://prntscr.com/fzbkco

**Comment by AnitaKirkovska** [comment]
I cant do it as well.

**Comment by mitrevski94** [comment]
UPDATE on the missing button: It is there but it is white(invisible) something like that.

**Comment by TsTrv** [comment]
Style issue on smaller devices isn't fixed yet.

**Comment by TsTrv** [comment]
> Style issue on smaller devices isn't fixed yet.

@ficiani have a look at this one if you get a chance.

**Comment by TsTrv** [comment]
Fixed by @trajchevska.
