### ISSUE TITLE
Listing showing 1 bed instead of 2 beds

### ISSUE THREAD

**Issue by AnitaKirkovska** [wetalkit/supercup#29]
I selected 2 beds, and it showed that I am offering 1. 
See issue #18: I think it is decrementing the value by 1.

![image](https://user-images.githubusercontent.com/24755827/28502476-86b0dd62-6ff3-11e7-8f82-7bb45d897f4f.png)

**Comment by trajchevska** [comment]
This is good now after fixing #18, but please check again just in case. It will only work for newly created listings, not for the old ones.

**Comment by TsTrv** [comment]
Fixed under #18
