### ISSUE TITLE
Property: Distance is represented by two different views

### ISSUE THREAD

**Issue by AnitaKirkovska** [wetalkit/supercup#31]
On some listings the distance shows KM, on others Walking distance. Is this right?

![image](https://user-images.githubusercontent.com/24755827/28502509-0e710664-6ff4-11e7-96af-34412bba9197.png)

**Comment by TsTrv** [comment]
Opening a discussion about this one. The idea is to show walking minutes for places that are less than 1-hour walk from the stadium. For the rest of them, we show distances in km. 

Closing this one, for now, let's reopen it once we have a decision.
