### ISSUE TITLE
No option for adding more than one photo.

### ISSUE THREAD

**Issue by mitrevski94** [wetalkit/supercup#33]
How can I add more then one photo when creating a listing? I should be able to do that in order for the slider to work on listing details.

**Comment by mitrevski94** [comment]
I see that I can add more pictures, but is this user friendly since I have to submit each time I add new picture?

**Comment by TsTrv** [comment]
There is a multiple select when you click on browse files. You can select as many as you want using CRL button. It is not very intuitive, but the best we could do considering the timeframe.

**Comment by TsTrv** [comment]
A new label has been added that specify that you could upload multiple files.
