### ISSUE TITLE
Iphone: I don't have the button "Message the Host"

### ISSUE THREAD

**Issue by AnitaKirkovska** [wetalkit/supercup#43]
When I go to some listing it doesnt show the button "message the host". Maybe it can be shown at the end of the page, before the footer.

![image](https://user-images.githubusercontent.com/24755827/28503029-e21522e8-6ffe-11e7-8d65-7396bdeb5338.png)

**Comment by AnitaKirkovska** [comment]
Now I have it but it is not showing properly. Maybe we should put it at the end?

![image](https://user-images.githubusercontent.com/24755827/28504179-929e20c0-7012-11e7-9943-82fbfa618e9c.png)

**Comment by trajchevska** [comment]
Fixed.
