### ISSUE TITLE
"Booked" button out of position [solution proposed] 

### ISSUE THREAD

**Issue by ficiani** [wetalkit/supercup#68]
![booked](https://user-images.githubusercontent.com/17123526/28505156-613355aa-7021-11e7-8331-aa4c63142c1b.png)

Right now the "Booked" button is positioned absolute (right 5% top 5%) to its parent element, so it goes to the very right:

Proposed solution: instead of the < img > tag in the HTML, make it a background image with size 'cover 'to each listing, it should fix the issue. @trajchevska

**Comment by TsTrv** [comment]
Fixed.
